# Generated by Django 4.2.11 on 2024-08-15 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                (
                    "documento_identificacao",
                    models.CharField(max_length=50, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("cor", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EntradaSaidaVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_entrada",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("hora_saida", models.DateTimeField(blank=True, null=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.veiculo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntradaSaidaPedestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_entrada",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("hora_saida", models.DateTimeField(blank=True, null=True)),
                (
                    "pedestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.pedestre"
                    ),
                ),
            ],
        ),
    ]
